#!/usr/bin/env bash
docker run \
    --name ace-test-db \
    --hostname ace-test-db \
    --rm \
    -e MYSQL_ROOT_PASSWORD=ace \
    --mount source=ace-test-db-volume,target=/var/lib/mysql \
    --mount "type=bind,source=/opt/ace/docker/mounts/mysql/init,target=/docker-entrypoint-initdb.d" \
    --network ace-test-network \
    --expose 3306 \
    -p 127.0.0.1:13306:3306/tcp \
    mysql:5.7 

