FROM ace-base:latest
USER root
RUN apt -y install git vim screen default-mysql-client man
USER ace
COPY --chown=ace:ace etc/vimrc /home/ace/.vimrc
WORKDIR /opt/ace
VOLUME [ "/opt/ace", "/opt/ace/data" ]
