#!/usr/bin/env bash
#
# installs and configures ACE gui for Apache
#

source installer/common.sh

# make sure the correct locale is set for supporting unicode characters
locale-gen --purge en_US.UTF-8
update-locale LANG=en_US.utf8
# uncomment the following for apache2 to use the system locale 
sed -i '/^#. \/etc\/default\/locale/s/^#//' /etc/apache2/envvars 

# have we already configured apache for ace?
if [ -L /etc/apache2/sites-available/ace.conf ]; then exit 0; fi

cp "$SAQ_HOME/etc/saq_apache.example.conf" "$SAQ_HOME/etc/saq_apache.conf"
ln -s "$SAQ_HOME/etc/saq_apache.conf" /etc/apache2/sites-available/ace.conf && \
a2ensite ace 

exit 0
