DROP USER IF EXISTS 'ace-superuser'@'%';
CREATE USER 'ace-superuser'@'%' IDENTIFIED BY 'ACE_SUPERUSER_DB_USER_PASSWORD';
GRANT ALL PRIVILEGES ON *.* TO 'ace-superuser'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
