#!/usr/bin/env bash

cd /opt/ace
source load_environment
source venv/bin/activate

for dir in \
    error_reports \
    logs \
    var \
    scan_failures \
    storage \
    vt_cache \
    stats \
    archive/email \
    archive/smtp_stream \
    archive/office \
    archive/ole
do
    if [ ! -d data/$dir ]
    then
        mkdir -p data/$dir
    fi
done

ace enc set -o -p ace
ace -L etc/debug_logging.ini -P ace service start ecs
ace -L etc/debug_logging.ini service start network_semaphore
ace -L etc/debug_logging.ini service start yara
ace -L etc/debug_logging.ini service start engine 
uwsgi --ini etc/web_uwsgi.ini
#uwsgi --ini etc/api_uwsgi.ini 
ace -L etc/debug_logging.ini service stop engine
ace -L etc/debug_logging.ini service stop yara
ace -L etc/debug_logging.ini service stop network_semaphore
ace -L etc/debug_logging.ini service stop ecs
