CREATE DATABASE IF NOT EXISTS `amc`;
ALTER DATABASE `amc` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
USE `amc`;

CREATE TABLE emails ( id BIGINT NOT NULL AUTO_INCREMENT, path VARCHAR(512) NOT NULL, PRIMARY KEY (id) );
CREATE UNIQUE INDEX i_emails_path ON emails(path);
